spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
#    hibernate:
#      ddl-auto: create

  flyway:
        baseline-on-migrate: true
        locations: classpath:db/migration/postgres
        enabled: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sensitive_word_database
    username: postgres
    password: sa

  swagger:
    enable: true

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true