spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
#    hibernate:
#      ddl-auto: create

  flyway:
        baseline-on-migrate: true
        locations: classpath:db/migration/postgres
        enabled: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_flyway_sensitive_word
    username: postgres
    password: sa

  swagger:
    enable: true
